#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 31 10:01:45 2020

@author: nburt
"""

import requests
import re
import json
from bs4 import BeautifulSoup

# https://medium.com/@janekmajewski/beginners-guide-to-web-scraping-with-beautiful-soup-on-london-rent-listings-1ab6824c11b8


def extract_listing_json(listing_url):
    page = requests.get(listing_url)
    bs = BeautifulSoup(page.text, 'lxml')
    
    js_script_text=bs.findAll("script",{'type':"text/javascript"})[0].string
    script_json=re.findall(("(?<=window.PAGE_MODEL = )(?s)(.*$)"),js_script_text)[0]
    json_data=json.loads(script_json)
    
    return(json_data)

listing_json = extract_listing_json("https://www.rightmove.co.uk/properties/100745492#/")

print(listing_json["propertyData"]["location"]["latitude"])

print(listing_json["propertyData"]["location"]["longitude"])

